apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: security-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global-with-backup
  resources:
    requests:
      storage: 2Gi
