---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security-apps
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    image:
      repository: vaultwarden/server
      tag: 1.25.1
    env:
      DATA_FOLDER: "config"
      DOMAIN: https://bitwarden.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "false"
      TZ: Europe/London
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
      DATABASE_URL: postgresql://vaultwarden:${SECRET_VAULTWARDEN_DB_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: adminToken
      YUBICO_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeyClientID
      YUBICO_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeySecretKey
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: bitwarden.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - "bitwarden.${SECRET_DOMAIN}"
            secretName: "bitwarden-tls"
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    postgresql:
      enabled: true
      postgresqlUsername: vaultwarden
      postgresqlPassword: ${SECRET_VAULTWARDEN_DB_PASSWORD}
      postgresqlDatabase: vaultwarden
      persistence:
        enabled: true
        existingClaim: vaultwarden-postgresql
        accessModes:
          - ReadWriteOnce
