apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-postgresql
  namespace: security-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
