---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
