# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ThmKettGjO9PNyh/mAOQDbh1,iv:pQWhaYlk3MEwIhfHnWUqWTKkuEVrSDztZ6NDxXusMJo=,tag:SQuFFYtLoskVeanPar1b/w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:EW0zxtkvMhd5wG+yureyi4xN62u3Y9+rvJOhx5J2xZnAGEmWqg==,iv:We6O1NzsqbTH3ifyjkf2Fap38F1Ke8hLyi9OpOglbaw=,tag:Mbv+hUJ473yKHpaEvneZ+A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:g0X/+LyqYt2KSkBweA==,iv:kA77dfbsr8CVODQYMgVOnuNAeNfXHJ4ikjw+ffhCHRU=,tag:o/Fu3Grh0gwXdmHNDsYTFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OFhLYkZyU0hMYXlKS28v
            R05aTmtrZTlHYzRUbXVSQ1N5MFB3S0gvazFvCkFFczlLdE8wNW9sNWdrRmNOdCs2
            SWJTaDhrV1dub3JZZDJydnEvemlGM00KLS0tIEtUbmowdnV2SGlRSU8vSEVnQU16
            bStmRENVSVdXTUI0ZHUyWERlSXJSVW8K+WhkYFzBaK51ec5LNaGbxt4byJzTNtTG
            9rm8caon8JP+cqf6R11axWS4nreCjSsxery+/e4E5rCcmgPFGMxOnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T13:28:14Z"
    mac: ENC[AES256_GCM,data:hLxXqxrBhx01rIj9Rzyo+fU2SNF8zkrrFlMAF/Yjexb9wLTrzy0esMC2lLnougai5u/b8OMWlYRL+dXca3jndvVFKjAs3Gq95jqOt34h1AVvRAy5Hx4BSBpy3f7t1UJT7m1lVbjdQ1rnjH0Bzhu2p2bmrswMRnHfJQ0xUFevxCo=,iv:gJZJnkAsBZKX2NRDM2FXc3Wyw1ck/ob3iWBqmQY6KNE=,tag:7bE/ajCyS5yRaC0IWTi0Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
