---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
