---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.25.0
    env:
      DATA_FOLDER: "config"
      DOMAIN: https://vaultwarden.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "true"
      TZ: "${CLUSTER_TZ}"
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
    envFrom:
      - secretRef:
          name: vaultwarden
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: vaultwarden.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub/negotiate
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                servicePort: 3012
        tls:
          - hosts:
              - vaultwarden.${SECRET_DOMAIN}
            secretName: "${SECRET_DOMAIN//./-}-tls"
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "vaultwarden.${SECRET_DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN//./-}-tls"
          - hosts:
              - "vaultwarden.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    postgresql:
      enabled: true
      postgresqlUsername: "${VAULTWARDEN_POSTGRES_USERNAME}"
      postgresqlPassword: "${VAULTWARDEN_POSTGRES_PASSWORD}"
      postgresqlDatabase: "${VAULTWARDEN_POSTGRES_DATABASE}"
      persistence:
        enabled: true
        storageClass: longhorn
        existingClaim: vaultwarden-postgres-v1
        accessModes:
          - ReadWriteOnce
