---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    image:
      repository: vaultwarden/server
      tag: v1.25.0
    env:
      DATA_FOLDER: "config"
      DOMAIN: https://vaultwarden.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "true"
      TZ: Europe/London
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
      DATABASE_URL: postgresql://vaultwarden:${SECRET_VAULTWARDEN_DB_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: vaultwarden.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - "vaultwarden.${SECRET_DOMAIN}"
            secretName: "vaultwarden-tls"
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "vaultwarden.${SECRET_DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
                service:
                  port: 80
        tls:
          - hosts:
              - "vaultwarden.${SECRET_DOMAIN}"
            secretName: "vaultwarden-tls"
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    postgresql:
      enabled: true
      postgresqlUsername: "${VAULTWARDEN_POSTGRES_USERNAME}"
      postgresqlPassword: "${VAULTWARDEN_POSTGRES_PASSWORD}"
      postgresqlDatabase: "${VAULTWARDEN_POSTGRES_DATABASE}"
      persistence:
        enabled: true
        existingClaim: vaultwarden-postgresql
        accessModes:
          - ReadWriteOnce
