apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-postgres-v1
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
