apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: security-apps
stringData:
    adminToken: ENC[AES256_GCM,data:fGpAk6qn2yV/Dqy4EK73Y5UaHWRtujtSyTlnP0Jb/+wN0fhq9KvohgtosXiqN/uvBAqnrMYr9X0dPvcAT3o4Tg==,iv:TOp3CwDS+x37uchxWn3cuk911xDE3tiojh6i8cKeX+Q=,tag:Bo+WjQUl0rrYTTHdt6puaQ==,type:str]
    yubikeyClientID: ENC[AES256_GCM,data:uRjin2w=,iv:qfCUY8HeHOvDQAmUQiIIkyQGe1706JkBxranOiTmO/E=,tag:DUhH5Jk1iZF8ClQKMcFjUg==,type:str]
    yubikeySecretKey: ENC[AES256_GCM,data:xe5SHxU4jzOfWo94kO3mEbeOC8BxSn4r9ET12w==,iv:38Hkr75bw9nOMA2reN2dASz7hPNzJn5Cvil2ukYzIgU=,tag:YhGn+4Zwz3vU4DRJLAfhPA==,type:str]
    SECRET_VAULTWARDEN_DB_PASSWORD: ENC[AES256_GCM,data:8JzSrNEdRB8ctlOhjzWQaqIqmgkuAEj4XHTrsRL4kMAl/Nc2l9VlA32Ajer/1ZFWqZvHtiUJLE0Ji0hBlJfbHA==,iv:MhCzhHKo4rxJWs9jbZHoAa6dXVFch92wLiQmjI3WPwI=,tag:IIRfNO61di5Jxv4IAchYeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0FBZ3kzajIxUC9BMHVY
            NTJHRFZyaGJreXlwRDVhUmJ5cWF5T3A1RGlvClUwZ3M2UC9nQ3lwZHU1U1oyZFQr
            RTBSY1lBRTQ3VCs1dytGdk1yVm1MdXMKLS0tIHk5eHdKdC8zUlIxRlMxWlN4TGow
            V1psbExvSzlZN3FWcDFhN3pVOTNzUUUKLfwSwQR11XqyUwbZeJTHQYorwVSMsa8l
            OwU66S+4bnll+P3gBlRfw1EG5/47MX7hgXfLTehSD/QSKGtSwoMo4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T11:11:28Z"
    mac: ENC[AES256_GCM,data:YGlL2nWFUoHvbW0W9wuDTDT78rjyY/VTEFYQK8vU4LbD8NYlf0S64KV89taPJJsNKg3zfswAZTJKQRXnmNwTUiUa730eE6OwvjZLcR2Pw8L5i+GBArZFRdJUL+01wuvEwfiUOtwGmjEfDmrYkd62VuvVS23j5edmCAv78QkDt6Y=,iv:TFYHU9KbWK30BHdnEmQpiVbuClDTcbJo0NxHZWjWIs4=,tag:BYuqNgRgbuPutxh4SMhoPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
