# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:HLics13hoIa5IaRF78SxAUHq,iv:pUVNNvBHht8zFd6VH1P55Sgj5d0cAZfUizXnAvKjtdw=,tag:1gC/xHjq5kWYsPpdnW29Aw==,type:str]
    api-key: ENC[AES256_GCM,data:uXFwI3xCjTHzAOZxlMnwDW9cCb9o+6Mricpgtke1+zV++F5qaw==,iv:umnw9YClJRlw5vCkKRDtYzhi8U/cjgtHvKmBVAPa3ZM=,tag:De7+uejR34Xv7NZWvXmMLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySmE3OVpYOTJJR2FPKzBy
            dnRrL09rd3JRSzNSVEZvL3M1cUN5OVpXdmdvCnRuM0I5VFVHSTNNeWZhUDB3aVJO
            SVRxOEdsZnVKc3V1OHl2WHBSZXg2ZVEKLS0tIHdJQ09jZzhDSW1RSmxOKzhMYlRT
            c3haSndUblJnRU5CdE1tZG5sUUwxRkkKOI0gpgA6otCD5glNKz/DoG+C3JgXdKPK
            0sEFjKSeTaO7jRGVaML6z4nxN+GaHey9Y4WqWvJJIpMxWi2kSYNx0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T12:52:12Z"
    mac: ENC[AES256_GCM,data:4Pq2DqPhl8gKXkp2+6lmuWbw/dFoyJr3QfALZn3W2MYqrJHfwdLUYJmTx2DnTAgSRVJNnoRVnRbC2gdcwLIxstRIhguy/bJyTar2JjL2wa0epBnzUnId0Jbn3WyrUHGlw1bh7E8VEXvjZeLY2aOErGlyPzlGK4IGMPYOaR3gWKY=,iv:RQbP0epoMa+IQVXmj/p7mveqvhv6Av6u6Kn0rO0Nlv0=,tag:dm2I9OAM/r9bEeqq8rafiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
