---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 192.168.54.110-192.168.54.250
  METALLB_K8S_GATEWAY_ADDR: 192.168.54.110
  METALLB_INGRESS_ADDR: 192.168.54.111
