# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rXjErw+OeOs=,iv:9CnZFzLbqiEEHBBJgTHa8xkvHycBunu6temb0yOslcw=,tag:ocAA7qBYh03WOtOKrEej0g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DccCAtj910vZTrcjKsYeXS7s,iv:L9eka+awTmXYBBwxlxWIQYCjsct2MyHiGxhoLqygCAE=,tag:MRe51rmTMHvYf7whvqQelA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZWkrYU5RU3haY3NVNWRT
            eDhqQVlhQnhjeGZCbXZQUlNTNm43SDhEUVdrCmdOVzYvV25SU0diU0xsalNSYUky
            L2dyOGR2bGtGZEhYWkdBOXpOMFhlR3cKLS0tIHZMVWlZaVo0MVZORXlLZnVQS0Jk
            Y3NBcGNqZTNUb0FTd0E3R2tWeWtsS28K8o3oaak40gTdwo7cOag4UKj+q0UA/qEv
            Pf4HvY9Raax1iDLreiqF6hEX8ToA/E0tvylLWno/Yr3VsDi2a7K2Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T12:52:12Z"
    mac: ENC[AES256_GCM,data:dmzW1egcYAnNe4z2a/RaJ2D6PlFp+a9A/m/1e3lTpIbyEp5Yo78rKtCAM1mBsIFtABNNU6QkCho0kaoZqvbbb9nQKu+6wDS/4vZ3a8icSENJmjEHUDoHu9/1mU+WY9XSAu0Z6r+ECYSZCxM1J+4+szKmYUsJubcmaItZ65kJcp8=,iv:l7DMPXQ2JEh4ekC+703l/uwB8S5tyKMkVYgPVOZzkAc=,tag:fW94GPIvK94wTvjJ9aSyhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
