---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultSettings:
      defaultDataPath: /mnt/lvm_raid1/k3s/longhorn
      defaultReplicaCount: 1
      backupTarget: {$AWS_ENDPOINTS}
      backupTargetCredentialSecret: longhorn-backup-secret
    persistence:
      defaultClassReplicaCount: 1
    service:
      ui:
        type: ClusterIP
