apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-lapi-config
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
