---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu-postgresql
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.12.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/postgresql
      tag: 14.2.0-debian-10-r28
    auth:
      username: mailu
      password: "${SECRET_MAILU_DB_PASSWORD}"
      database: mailu
    primary:
      persistence:
        enabled: true
        existingClaim: mailu-postgresql
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
