# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pxwbcHsjbn7qS2Pc1tuq6ixnH6lT5Vx31WxUQSLUOCYlOl0wIjkJpQ==,iv:JwTQ47prN4NsNXQQwJi+If2SR+yWQso46/dRj4qjGzA=,tag:eWd4HrtIriOHh//+k2eMcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vnf98cueysmhz2vumkrg3889dn7v672tyccqfwz8l5k4fcfucgshzgfh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORGpYWTVGYlJPY1JpWlNi
            VjJoeXMvTFE1dVYzMWV4dTloUGFIMzRJeldzClU2T2ZaTW1Ma1NzMHBtM0owOFg0
            ZGtKdkxkdXhZZ2wzc0h1ZEdhbFJ2K3cKLS0tIFgraDFQVGdtaE5JQXRXandKSUxE
            N1dYU3JZVEdLUzRKa1Z4TmZRa2hicXMKctoAUKz6NteTq8V3l63QimvDr14BmzHL
            5zdq8fQ0NlQxv4Xd5RPgPu7u6IrfBICnhECbTw18JYz+HmbAadXrpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T16:31:11Z"
    mac: ENC[AES256_GCM,data:8fX4DzpGmdoPkcrYxI1fj2dTr1CGlrXMsjkO2dyMUG1q9xDkJmv8yWLw/fMzINMGmR9aV4//Z9l6fJiLRL+xnyZFYheU7fi8G3KCPHDjBmD69f4IAxU/vbStPGnKi0RpdPahV92ioBCJDaiOcysbe3hpMWnAjD+XWx39E9/Z8gk=,iv:LmyvnmoQGAZJQ4rC8k17Qh7cRf4BpMsI32Bgelsb1sM=,tag:EL666rKo1Q8j05M2QxUYtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
